### ISSUE TITLE
《make a face》problems

### ISSUE THREAD

**Issue by super3kl** [TheSouthFrog/stylealign#10]
Hi，recently，i have been reading the paper 《Make a Face: Towards Arbitrary High Fidelity Face Manipulation》. 
i am still confused about the paper and have a lot of problems. i just wonder whether you have the thought of open source of this paper. i will appreciate it very much if you do. 
thankyou very much.

**Comment by TheSouthFrog** [comment]
Sorry, we don't have a plan on open-sourcing that project. 

If you have some questions regarding the other paper, we can discuss it through e-mail. You can reach me via my e-mail thesouthfrog@gmail.com.

Best,
Shengju
