### ISSUE TITLE
AFLW with new  68-point  annotation

### ISSUE THREAD

**Issue by xjcvip007** [TheSouthFrog/stylealign#3]
Thank you for your amazing job, do you release your link about AFLW with new 68-point annotation?

**Comment by TheSouthFrog** [comment]
We are still working on it in terms of data preparation and release. Hopefully, it would be released soon.

**Comment by yuxwind** [comment]
Hi @TheSouthFrog, thanks for your great job! Have you already released the dataset somewhere? Could you share the link?
