### ISSUE TITLE
pretrained checkpoint for testing?

### ISSUE THREAD

**Issue by yl1991** [TheSouthFrog/stylealign#4]
Hi,
Do you plan to release pretrained checkpoints for testing?
Many thanks.

**Comment by TheSouthFrog** [comment]
Hi,

Thanks for your interest. I will release a pre-trained checkpoint on WFLW dataset. However, the code in this repo is cleaned up and has some difference compared with the old one I used for training. So I need to re-train the model using the new codebase and it may take several days. You may train one using the provided script or refer to the synthesized WFLW if you are in a hurry. The results should be similar.
